# Generated by Django 5.0.4 on 2024-07-12 16:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='paragraph',
            old_name='sub_title',
            new_name='title',
        ),
    ]
