# Generated by Django 5.0.4 on 2024-07-18 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_tag'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tag',
            options={'verbose_name': 'هشتگ', 'verbose_name_plural': 'هشتگ ها'},
        ),
        migrations.AddField(
            model_name='blog',
            name='tags',
            field=models.ManyToManyField(related_name='blogs', to='blog.tag', verbose_name='هشتگ ها'),
        ),
    ]
