# Generated by Django 5.0.4 on 2024-07-18 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_alter_tag_options_blog_tags'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tag',
            options={'get_latest_by': 'is_trend', 'ordering': ['is_trend'], 'verbose_name': 'هشتگ', 'verbose_name_plural': 'هشتگ ها'},
        ),
        migrations.AddField(
            model_name='tag',
            name='is_trend',
            field=models.BooleanField(default=False, verbose_name='ترند'),
        ),
    ]
