# Generated by Django 5.0.4 on 2024-07-17 17:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_alter_orderitem_ordered_at_alter_orderitem_quantity'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ('is_ordered', '-created_at'), 'verbose_name': 'سفارش', 'verbose_name_plural': 'سفارشات'},
        ),
    ]
