# Generated by Django 5.0.4 on 2024-07-19 09:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_address'),
        ('cart', '0004_alter_order_options_alter_order_is_ordered'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='address',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order', to='account.address', verbose_name='گیرنده'),
        ),
    ]
