# Generated by Django 5.0.4 on 2024-07-21 12:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_alter_faaliat_options_faaliat_created_at'),
        ('cart', '0008_rename_predicted_date_order_saved_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order', to='account.address', verbose_name='گیرنده'),
        ),
    ]
