# Generated by Django 5.0.4 on 2024-07-19 09:17

import django.db.models.deletion
import phonenumber_field.modelfields
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_alter_user_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, verbose_name='نام گیرنده')),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, verbose_name='شماره تماس گیرنده')),
                ('province', models.CharField(max_length=128, verbose_name='استان')),
                ('city', models.CharField(max_length=128, verbose_name='شهر')),
                ('address', models.TextField(verbose_name='آدرس پستی')),
                ('zip_code', models.CharField(max_length=128, verbose_name='کد پستی')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='addresses', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
