# Generated by Django 5.0.4 on 2024-07-21 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_faaliat'),
    ]

    operations = [
        migrations.AddField(
            model_name='faaliat',
            name='link',
            field=models.CharField(default='', max_length=255, verbose_name='نوع'),
            preserve_default=False,
        ),
    ]
