# Generated by Django 5.0.4 on 2024-07-21 09:28

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_faaliat_link'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='faaliat',
            options={'ordering': ('-created_at',), 'verbose_name': 'فعالیت', 'verbose_name_plural': 'فعالیت ها'},
        ),
        migrations.AddField(
            model_name='faaliat',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
