# Generated by Django 5.0.4 on 2024-07-15 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='author_pictures'),
        ),
        migrations.AlterField(
            model_name='genre',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='genre_pictures'),
        ),
        migrations.AlterField(
            model_name='interpreter',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='interpreter_pictures'),
        ),
        migrations.AlterField(
            model_name='publishing_company',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='publishing_company_pictures'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='subject_pictures'),
        ),
    ]
