# Generated by Django 5.0.4 on 2024-07-15 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0002_alter_author_image_alter_genre_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='height',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='width',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
