# Generated by Django 5.0.4 on 2024-07-15 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0003_alter_book_height_alter_book_width'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='description',
        ),
        migrations.AddField(
            model_name='book',
            name='introduction',
            field=models.TextField(default='کتاب جایی که خرچنگ ها آواز می خوانند نوشته ی دلیا اونز، از پرفروش ترین آثار سال 2018 و 2019 به شمار می رود و داستان جنایی و جذاب دختری است که اعضای خانواده اش او را در سنین خردسالی رها کرده اند تا تنهایی، در دل طبیعت بکر کارولینای شمالی، با پدر کج خلقش زندگی کند. جایی که خرچنگ ها آواز می خوانند (Where the Crawdads Sing) به مدت 45 هفته در صدر لیست پرفروش ترین کتاب های جهان بوده است و می تواند به افسانه ای بی بدیل تبدیل شود. این رمان با قلب تان بازی می کند و موضوعی جدید در ترکیب انزوا و طبیعت از دیدگاه یک نویسنده ی خانم در خلال عشقی را روایت می کند که بیشتر حالت توفیق اجباری دارد.این اثر یک درام جنایی، عاشقانه و معمایی است که شما عاشقش خواهید شد. این رمان به تار و پود طبیعت تان سفر می کند و سوالاتی بی پاسخ می پرسد، سوالاتی که قدمتی به اندازه ی مرداب دارند. این کتاب شرح حالی از تلاش برای بقا، امید داشتن، عشق ورزیدن، تنهایی، نومیدی، غرور، تعصب و انعطاف پذیری است.', verbose_name='معرفی کتاب'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='book',
            name='credit',
            field=models.DecimalField(decimal_places=0, max_digits=10, verbose_name='قیمت'),
        ),
    ]
