# Generated by Django 5.0.4 on 2024-07-15 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0004_remove_book_description_book_introduction_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='description',
            field=models.TextField(default='دلیا اونز متولد سال 1949 میلادی در آمریکا، نویسنده و جانور شناس می باشد. اولین رمان وی به نام جایی که خرچنگ ها آواز می خوانند، هفته ها در صدر بیشترین فروش کتاب های تخیلی 2019 نیویورک تایمز بود. او همچنین نویسنده خاطرات گریه های کالاهاری، چشم های فیل، و راز های ساوانا، درباره ی مطالعات حیوانات در آفریقا می باشد. اونز "بنیاد اونز" برای حفاظت از حیات وحش را در آمریکا تاسیس کرد.', verbose_name='درباره نویسنده'),
            preserve_default=False,
        ),
    ]
