# Generated by Django 5.0.4 on 2024-07-15 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0005_author_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Achievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='book',
            name='achievements',
            field=models.ManyToManyField(related_name='books', to='book.achievement', verbose_name='افتخارات کتاب'),
        ),
    ]
