# Generated by Django 5.0.4 on 2024-07-15 11:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0006_achievement_book_achievements'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='genres',
            field=models.ManyToManyField(related_name='books', to='book.genre', verbose_name='ژانر'),
        ),
        migrations.AlterField(
            model_name='book',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='books', to='book.subject', verbose_name='دسته بندی موضوعی'),
        ),
    ]
