# Generated by Django 5.0.4 on 2024-07-16 12:07

import isbn_field.fields
import isbn_field.validators
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0008_alter_book_options_alter_subject_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='achievement',
            options={'verbose_name': 'افتخار', 'verbose_name_plural': 'افتخارات'},
        ),
        migrations.AlterModelOptions(
            name='author',
            options={'verbose_name': 'نویسنده', 'verbose_name_plural': 'نویسندگان'},
        ),
        migrations.AlterModelOptions(
            name='genre',
            options={'verbose_name': 'ژانر', 'verbose_name_plural': 'ژانرها'},
        ),
        migrations.AlterModelOptions(
            name='interpreter',
            options={'verbose_name': 'مترجم', 'verbose_name_plural': 'مترجمین'},
        ),
        migrations.AlterModelOptions(
            name='publishing_company',
            options={'verbose_name': 'نشریه', 'verbose_name_plural': 'ناشرین'},
        ),
        migrations.AlterModelOptions(
            name='subject',
            options={'verbose_name': 'دسته بندی موضوعی', 'verbose_name_plural': 'موضوعات'},
        ),
        migrations.AlterField(
            model_name='book',
            name='isbn',
            field=isbn_field.fields.ISBNField(max_length=20, validators=[isbn_field.validators.ISBNValidator], verbose_name='شابک'),
        ),
    ]
