# Generated by Django 5.0.4 on 2024-07-16 12:54

import book.models
import django.db.models.deletion
import isbn_field.fields
import isbn_field.validators
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0009_alter_achievement_options_alter_author_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Literature',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, verbose_name='نام')),
                ('image', models.ImageField(blank=True, null=True, upload_to='international_pictures', verbose_name='تصویر')),
                ('description', models.TextField(blank=True, verbose_name='توضیحات')),
            ],
            options={
                'verbose_name': 'ادبیه ملت',
                'verbose_name_plural': 'ادبیات ملل',
            },
        ),
        migrations.AlterField(
            model_name='book',
            name='achievements',
            field=models.ManyToManyField(blank=True, related_name='books', to='book.achievement', verbose_name='افتخارات کتاب'),
        ),
        migrations.AlterField(
            model_name='book',
            name='isbn',
            field=isbn_field.fields.ISBNField(max_length=28, validators=[isbn_field.validators.ISBNValidator], verbose_name='شابک'),
        ),
        migrations.AddField(
            model_name='book',
            name='literature',
            field=models.ForeignKey(blank=True, default=book.models.Literature.get_default_pk, on_delete=django.db.models.deletion.PROTECT, related_name='books', to='book.literature', verbose_name='ادبیات ملل'),
        ),
    ]
