# Generated by Django 5.0.4 on 2024-07-16 14:07

import django.db.models.deletion
import django.db.models.query
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0011_remove_book_subject_alter_book_literature'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='subject',
            field=models.ForeignKey(default='2672214a-6c46-466b-b000-13153c3b4f9d', on_delete=django.db.models.deletion.PROTECT, related_name='books', to='book.subject', verbose_name='دسته بندی موضوعی'),
        ),
    ]
