# Generated by Django 5.0.4 on 2024-07-16 14:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0013_book_subject'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='books', to='book.subject', verbose_name='دسته بندی موضوعی'),
        ),
    ]
