# Generated by Django 5.0.4 on 2024-07-21 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_alter_tag_name_like'),
        ('book', '0015_publishing_company_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='tags',
            field=models.ManyToManyField(related_name='books', to='blog.tag', verbose_name='هشتگ ها'),
        ),
    ]
